// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGWuzZG0khL30HVUnkkFtNR6ZP4y7UDSQ',
    appId: '1:426057887932:web:4aab6f7f752ddc9786e0b9',
    messagingSenderId: '426057887932',
    projectId: 'cashjon-a4975',
    authDomain: 'cashjon-a4975.firebaseapp.com',
    storageBucket: 'cashjon-a4975.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdsXBrlCCNK3IWyIlqvY5HSPyYNPnVD8E',
    appId: '1:426057887932:android:295d749b28f6e92186e0b9',
    messagingSenderId: '426057887932',
    projectId: 'cashjon-a4975',
    storageBucket: 'cashjon-a4975.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBsu8T_W19iLlbdFcu2d47acVPffC-HjA',
    appId: '1:426057887932:ios:9c2683a1c96b5ffa86e0b9',
    messagingSenderId: '426057887932',
    projectId: 'cashjon-a4975',
    storageBucket: 'cashjon-a4975.appspot.com',
    iosClientId: '426057887932-bke4eldc1ph3udap5ircmnjuvt5ldts1.apps.googleusercontent.com',
    iosBundleId: 'com.example.cashJon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBsu8T_W19iLlbdFcu2d47acVPffC-HjA',
    appId: '1:426057887932:ios:9c2683a1c96b5ffa86e0b9',
    messagingSenderId: '426057887932',
    projectId: 'cashjon-a4975',
    storageBucket: 'cashjon-a4975.appspot.com',
    iosClientId: '426057887932-bke4eldc1ph3udap5ircmnjuvt5ldts1.apps.googleusercontent.com',
    iosBundleId: 'com.example.cashJon',
  );
}
